title: "Portfolio – Farshâd Mahjoub"
description: "Tierpflege & pädagogischer Bauernhof"
lang: de
timezone: Europe/Berlin

text_skin: forest
highlight_theme: default

# TeXt Theme (remote)
remote_theme: kitian616/jekyll-TeXt-theme

plugins:
  - jekyll-remote-theme

# URL settings (optional; GitHub Pages setzt das automatisch)
# url: "https://USERNAME.github.io"
# baseurl: ""

# Optional: Social / footer
author:
  name: "[Name]"
